# -*- mode: ruby -*-
# vi: set ft=ruby :


SERVICES =  {
  'iaschneiS' => {
  ip: '192.168.56.110',
  ports: { 8080 => 8080 }
  },
  'iaschneiSW' => {
    ip: '192.168.56.111',
    ports: { 8181 => 8181 }
  }
}

# The argument '2' corresponds to the config version. 2 is the most recent version. 
Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/debian12"

  config.vm.define "iaschneiS" do |iaschneiS|
    iaschneiS.vm.hostname = "iaschneiS"
    iaschneiS.vm.network = "private_network", ip: SERVICES['iaschneiS'][:ip]
    iaschneiS.vm.network = "forwarded_port", guest: 8080, host: 8080

    iaschneiS.vm.provision "shell", name: "start-iaschneiS", inline: <<-SHELL
      apt update && apt upgrade -y
      ufw disable
    SHELL
  end

  config.vm.define "iaschneiSW" do |iaschneiSW|
    iaschneiSW.vm.hostname = "iaschneiSW"
    iaschneiSW.vm.network = "private_network", ip: SERVICES['iaschneiSW'][:ip]
    iaschneiSW.vm.network = "forwarded_port", guest: 8181, host: 8181

    iaschneiSW.vm.provision "shell", name: "start-iaschneiSW", inline: <<-SHELL
      apt update
    SHELL
  end
end
