# -*- mode: ruby -*-
# vi: set ft=ruby :

machines=[
  {
    :hostname => "iaschneiS",
    :ip => "192.168.56.110",
    :box => "generic/debian12",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "iaschneiSW",
    :ip => "192.168.56.111",
    :box => "generic/debian12",
    :ram => 1024,
    :cpu => 2
  }
]

# The argument '2' corresponds to the config version. 2 is the most recent version. 
Vagrant.configure("2") do |config|

  machines.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end

      node.vm.provision "shell", inline: case machine[:hostname]
     when "iaschneiS"
        <<-SHELL
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubelet kubeadm kubectl
          curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --token 12345" sh -s
        SHELL
      when "iaschneiSW"
        <<-SHELL
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubelet kubeadm kubectl
          curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" K3S_TOKEN="12345" INSTALL_K3S_EXEC="agent" sh -s
        SHELL
      end
    end
  end
end
